### ISSUE TITLE
Location of config-files

### ISSUE THREAD

**Issue by ScuttleSE** [unix-streamdeck/streamdeckd#12]
I suggest moving config files to $XDG_CONFIG_HOME/streamdeck, or similar, instead of putting the config directly in $HOME. 

What with the streamdeck requiring multiple resources, it would be nice with a common place to put it all.

**Comment by andydotxyz** [comment]
Maybe in Fyne's `App.Storage().RootURI()` perhaps - that picks based on OS, based on XDG_CONFIG_HOME for linux

**Comment by The-Jonsey** [comment]
Resolved in v1.0.1
