### ISSUE TITLE
No support for Streamdeck Mk 2

### ISSUE THREAD

**Issue by ymauray** [unix-streamdeck/streamdeckd#13]
In the driver, there is no support for the Streamdeck Mk 2 :

```
Path:"0001:000b:00"
VendorID:4057 = 0xfd9
ProductID:128 = 0x80
Release:512 = 0x200
Serial:"DL34K1A04150"
Manufacturer:"Elgato"
Product:"Stream Deck MK.2"
UsagePage:0 = 0x0
Usage:0 = 0x0
Interface:0
```

Upstream is 10 commit ahead, and does support the Mk2.

Would it be possible to refresh the driver ? 

Thanks.

**Comment by The-Jonsey** [comment]
Just updated the driver to the newest version, could you give it another try?

**Comment by ymauray** [comment]
Yes, it's all good! You can release it. Thanks!

**Comment by ymauray** [comment]
Hello. Could you publish a new release with this fix? I'm working on a couple of plugins, and I'd like to compile them against the latest version that includes the Mk 2. Thanks!

**Comment by andydotxyz** [comment]
You know you can just use the SHA as version number right? :)

**Comment by ymauray** [comment]
yes, but other people will most likely use the release version, and a plugin fails to load if it has been compiled with another version of streamdeckd.
i.e., I can use and compile my plugin using the SHA, but my friends won't be able to use it unless they also get the SHA'ed version of streamdeckd.

**Comment by The-Jonsey** [comment]
A new release has been made, v1.0.2

**Comment by ymauray** [comment]
Awesome, thank you!
